### ISSUE TITLE
Test just "Loading..."

### ISSUE THREAD

**Issue by loopy321** [Andrei0105/cgm-calibration#1]
This looks great, but when I go to: https://cgm-calibration-stats.azurewebsites.net/
and enter the following in the boxes, it just says "Loading..." and never does anything else.

https://nsxxxx.herokuapp.com
doctor-xxxxxxxxxxxxxxxx

I confirmed the site loads in "incognito" mode with:
https://nsxxxx.herokuapp.com/?token=doctor-xxxxxxxxxxxxxxx

**Comment by Andrei0105** [comment]
Hi! Currently no errors are being handled, so if there is an error the Loading... message will continue to be displayed. You can open the console to check if there was an error, and paste the error contents here (while hiding the site name and token). I will work to address some errors later today.

**Comment by loopy321** [comment]
This is the console output:

- Access to fetch at 'https://nsxxxx.herokuapp.com/api/v3/treatments?&sort$desc=date&limit=10&fields=eventType,created_at&eventType$in=Sensor%20Start&now=1592920586889&token=doctor-xxxxxxxxxxx'      (index):1    from origin 'https://cgm-calibration-stats.azurewebsites.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

- Failed to load resource: net::ERR_FAILED    nsxxxx.herokuapp.com/api/v3/treatments?&sort$desc=date&limit=10&fields=eventType,created_at&eventType$in=Sensor%20Start&now=1592920586889&token=doctor-xxxxxxxx:1 

- Uncaught (in promise) TypeError: Failed to fetch     asyncToGenerator.js:6

**Comment by Andrei0105** [comment]
What do you get if you access the following in a browser window:
`https://nsxxxx.herokuapp.com/api/v3/treatments?&sort$desc=date&limit=10&fields=eventType,created_at&eventType$in=Sensor%20Start&now=MILLIS&token=doctor-xxxxxxxxxxx`, with your site and token, and replacing MILLIS with the values copied from here https://currentmillis.com/. Also check if there is any error in the console.

When a new sensor is started, Spike adds a `Sensor Start` record to Nightscout. If you go to Nightscout reports, you should be able to see sensor starts in the Calibration report like this:
![start](https://user-images.githubusercontent.com/16063287/85417370-6ccf3800-b567-11ea-8a99-ae5f64f0b7b4.PNG)

**Comment by loopy321** [comment]
This is the text of the output:

- [{"created_at":"2020-06-21T19:55:37.000Z","eventType":"Sensor Start"},{"eventType":"Sensor Start","created_at":"2020-06-05T18:15:49.000Z"},{"eventType":"Sensor Start","created_at":"2020-05-15T17:28:18.000Z"},{"eventType":"Sensor Start","created_at":"2020-04-28T17:48:39.000Z"},{"eventType":"Sensor Start","created_at":"2020-04-10T21:39:39.000Z"},{"created_at":"2020-03-23T14:50:50.000Z","eventType":"Sensor Start"},{"eventType":"Sensor Start","created_at":"2020-02-20T23:23:07.877Z"},{"eventType":"Sensor Start","created_at":"2020-02-20T23:17:22.000Z"},{"eventType":"Sensor Start","created_at":"2020-02-20T23:17:05.000Z"},{"eventType":"Sensor Start","created_at":"2020-02-11T10:03:00.000Z"}]

Console:

- Failed to load resource: the server responded with a status of 404 (Not Found)       /favicon.ico:1

**Comment by Andrei0105** [comment]
Can you check if you have 'cors' in the ENABLE config variable in heroku? I thought that this was added by default, but it might not be. If it isn't there, add it and try to run the app again, checking the console for any errors.

![cors](https://user-images.githubusercontent.com/16063287/85418354-96d52a00-b568-11ea-9fe5-98d1ff75d3ed.PNG)

**Comment by loopy321** [comment]
That did it!  Added CORS to ENABLE as you suggested and now it loads.  
Thanks!!
